/* Automation Studio generated header file */
/* Do not edit ! */

#ifndef _LIBRARIES_20231031084308_
#define _LIBRARIES_20231031084308_

__asm__(".section \".plc\"");

/* Used IEC files */
__asm__(".ascii \"iecfile \\\"Logical/Libraries/operator/operator.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/operator/operator.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/operator/operator.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/runtime/runtime.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/runtime/runtime.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/runtime/runtime.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/astime/astime.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/astime/astime.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/astime/astime.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIecCon/AsIecCon.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIecCon/AsIecCon.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIecCon/AsIecCon.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/sys_lib/sys_lib.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/sys_lib/sys_lib.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/sys_lib/sys_lib.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsBrStr/AsBrStr.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsBrStr/AsBrStr.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsBrStr/AsBrStr.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/ArEventLog/ArEventLog.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/ArEventLog/ArEventLog.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/ArEventLog/ArEventLog.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/FileIO/FileIO.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/FileIO/FileIO.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/FileIO/FileIO.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/standard/standard.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/standard/standard.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/standard/standard.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsArLog/AsArLog.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsArLog/AsArLog.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsArLog/AsArLog.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsBrWStr/AsBrWStr.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsBrWStr/AsBrWStr.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsBrWStr/AsBrWStr.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"C:/Projects/Loupe/ErrorLib/src/Ar/ErrorLib/ErrorLib.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"C:/Projects/Loupe/ErrorLib/src/Ar/ErrorLib/ErrorLib.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"C:/Projects/Loupe/ErrorLib/src/Ar/ErrorLib/ErrorLib.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"C:/Projects/Loupe/ErrorLib/src/Ar/ErrorLib/ErrorLib_enum.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"C:/Projects/Loupe/ErrorLib/src/Ar/ErrorLib/ErrorCollector.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"C:/Projects/Loupe/ErrorLib/src/Ar/ErrorLib/ErrorCollector_HMI.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/piper/Piper.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/piper/Piper.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/piper/Piper.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/logthat/Types.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/logthat/Constants.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/logthat/LogThat.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/stringext/StringExt.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/stringext/StringExt.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/stringext/StringExt.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/hmitools/HMITools.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/hmitools/HMITools.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/hmitools/HMITools.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/hmitools/HMI_Basic.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/hmitools/HMI_Basic.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/hmitools/HMI_File_Browse.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/hmitools/LogViewer.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/hmitools/EditorControl.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/hmitools/HMI_Trend.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/hmitools/RecipeMgr.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/hmitools/Updater.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/ringbuflib/RingBufLib.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Loupe/ringbuflib/RingBufLib.fun\\\" scope \\\"global\\\"\\n\"");

/* Exported library functions and function blocks */
#ifdef _OPERATOR_EXPORT
	__asm__(".ascii \"plcexport \\\"SIZEOF\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ADR\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ADRINST\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SHR\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ROR\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ROL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SHL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AND\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"XOR\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"OR\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"NOT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ADD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MUL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SUB\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DIV\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MOVE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MAX\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MIN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LIMIT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SEL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MUX\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"GE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EQ\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"GT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"NE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ABS\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SQRT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LOG\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EXP\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SIN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"COS\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TAN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ASIN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ACOS\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ATAN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EXPT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TRUNC\\\" FUN\\n\"");
#endif
#ifdef _RUNTIME_EXPORT
	__asm__(".ascii \"plcexport \\\"r_trig\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"f_trig\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"rf_trig\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"GetTime\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SFCActionControl\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SFCAC2\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"RealTan\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealAtan\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealAsin\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealAcos\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealExp\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealLn\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealLog\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealExpt\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealAbs\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealSin\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealCos\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RealSqrt\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SFCAC3\\\" FUB\\n\"");
#endif
#ifdef _ASTIME_EXPORT
	__asm__(".ascii \"plcexport \\\"DTExSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DTSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DTGetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"clock_ms\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTGetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTExSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DTStructureGetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DTStructureSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DTStructureExSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTStructureGetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTStructureSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTStructureExSetTime\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDT_TO_LocalDTStructure\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LocalDT_TO_UtcDTStructure\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"UtcDTStructure_TO_LocalDT\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LocalDTStructure_TO_UtcDT\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ascTIMEStructure\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ascDTStructure\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ascTIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ascDT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIMEStructure_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_TIMEStructure\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DTStructure_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_DTStructure\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DiffT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DiffDT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TimeDeviceGetInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DstGetInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DstGetInfoDT\\\" FUB\\n\"");
#endif
#ifdef _ASIECCON_EXPORT
	__asm__(".ascii \"plcexport \\\"swapDT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapTIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapDATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapTOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapLREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapUDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapUINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"swapDWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HDT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HTIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HDATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HTOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HLREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HUDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HUINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"N_TO_HINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NDT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NTIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NDATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NTOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NLREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NUDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NUINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"H_TO_NINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BOOL_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BYTE_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WORD_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DWORD_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"USINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UDINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIME_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DATE_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TOD_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REAL_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LREAL_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"STRING_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"WSTRING_TO_STRING\\\" FUN\\n\"");
#endif
#ifdef _SYS_LIB_EXPORT
	__asm__(".ascii \"plcexport \\\"Byte2Bit\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"Bit2Byte\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"KEY_read\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"KEY_enadis\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_fix\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_info\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_copy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_store\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_burn\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_delete\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_ident\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_read\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_write\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DA_create\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DIS_clr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DIS_chr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DIS_str\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ERRxfatal\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ERR_read\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ERRxread\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ERR_fatal\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ERR_warning\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ERRxwarning\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SM_release\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SM_attach\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SM_delete\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SM_ident\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SM_create\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIM_ticks\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TIM_musec\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SW_settime\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SW_gettime\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RTC_settime\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RTC_gettime\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TMP_free\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TMP_alloc\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MEM_free\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MEM_alloc\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AVT_info\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AVT_release\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AVT_attach\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AVT_ident\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AVT_cancel\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"AVT_create\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_sleep\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_exit\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_freemsg\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_recmsg\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_sendmsg\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_resume\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_suspend\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"UT_ident\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_name\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_info\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_allsuspend\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_tmp_resume\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_tmp_suspend\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_resume\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_suspend\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ST_ident\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"FORCE_info\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MO_ver\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MO_list\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MO_info\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SYS_battery\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SYSreset\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SYSxinfo\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SYS_info\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_xlist\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_ninfo\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_item\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_ident\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_list\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_info\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_xgetval\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_xsetval\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_xgetadr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_getadr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_getval\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PV_setval\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"slMoList\\\" FUB\\n\"");
#endif
#ifdef _ASBRSTR_EXPORT
	__asm__(".ascii \"plcexport \\\"brsftoa\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsatof\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsatod\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsitoa\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsatoi\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsmemset\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsmemcpy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsmemmove\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsmemcmp\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsstrcat\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsstrlen\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsstrcpy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brsstrcmp\\\" FUN\\n\"");
#endif
#ifdef _AREVENTLOG_EXPORT
	__asm__(".ascii \"plcexport \\\"ArEventLogCreate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogDelete\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogGetIdent\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogWrite\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogGetLatestRecordID\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogGetPreviousRecordID\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogRead\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogReadDescription\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogReadErrorNumber\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogReadAddData\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogReadObjectID\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogMakeEventID\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogIsError\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogIsWarning\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogIsInformation\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogIsSuccess\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogIsCustomerArea\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogAddDataInit\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogAddDataUdint\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogAddDataDint\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogAddDataString\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ArEventLogAddDataQuantity\\\" FUN\\n\"");
#endif
#ifdef _FILEIO_EXPORT
	__asm__(".ascii \"plcexport \\\"FileCreate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileOpen\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileClose\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileRead\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileReadEx\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileWrite\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileWriteEx\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileRename\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileCopy\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileDelete\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileTruncate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirCreate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirOpen\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirClose\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirRead\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirReadEx\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirRename\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirCopy\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirDelete\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DirDeleteEx\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SetAttributes\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"GetAttributes\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DevMemInfo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DevLink\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"DevUnlink\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"GetVolumeLabel\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"GetVolumeSerialNo\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"FileIoGetSysError\\\" FUN\\n\"");
#endif
#ifdef _STANDARD_EXPORT
	__asm__(".ascii \"plcexport \\\"RF_TRIG\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CTUD\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CTD\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"CTU\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"F_TRIG\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"R_TRIG\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SR\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"RS\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"SEMA\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TON\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TOF\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TP\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TON_10ms\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TOF_10ms\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"TP_10ms\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LEN\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LEFT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RIGHT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"MID\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"CONCAT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"INSERT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DELETE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"REPLACE\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"FIND\\\" FUN\\n\"");
#endif
#ifdef _ASARLOG_EXPORT
	__asm__(".ascii \"plcexport \\\"AsArLogCreate\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"AsArLogDelete\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"AsArLogWrite\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"AsArLogRead\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"AsArLogClear\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"AsArLogGetInfo\\\" FUB\\n\"");
#endif
#ifdef _ASBRWSTR_EXPORT
	__asm__(".ascii \"plcexport \\\"brwcsconv\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brwcsncpy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brwcsncat\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brwcscat\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brwcscmp\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brwcslen\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brwcsset\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brwcsncmp\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brwcscpy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brwcsrchr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"brwcschr\\\" FUN\\n\"");
#endif
#ifdef _ERRORLIB_EXPORT
	__asm__(".ascii \"plcexport \\\"errcolAddSourceByAddress\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"errcolAddSourceByName\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"errcolAddError\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"errcolAcknowledge\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ErrorCollectorFn_Init\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ErrorCollectorFn_Cyclic\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ErrorCollectorFn_HMI_Cyclic\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"errcolInternalSetError\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"errcolIntGenerateDisplayString\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"errcolInternalAddError\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"errcolInternalLogError\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"errcolInternalLogAcknowledge\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"errcolInternalRemoveError\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"errcolInternalRefreshHMIDisplay\\\" FUN\\n\"");
#endif
#ifdef _PIPER_EXPORT
	__asm__(".ascii \"plcexport \\\"Piper_fn_Cyclic\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"Piper_Module_Fub\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"Piper_setCommand\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"Piper_checkResponses\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"Piper_handleResponseState\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"Piper_PackML\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PackMLStateString\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"PiperStateChange\\\" FUN\\n\"");
#endif
#ifdef _LOGTHAT_EXPORT
	__asm__(".ascii \"plcexport \\\"logDelete\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"createLogInit\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"logEventID\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"logSuccess\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"logWarning\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"logError\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"logInfo\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"logStateChange\\\" FUB\\n\"");
#endif
#ifdef _STRINGEXT_EXPORT
	__asm__(".ascii \"plcexport \\\"lstrip\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"rstrip\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"atoui\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"uitoa\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ByteToHexString\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"HexStringToDINT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"GenerateTimestampMS_1\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"GenerateTimestampMS\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"GenerateTimestamp\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"strncat4\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ToUpper\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ToLower\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"Timestamp_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"appendArrayIndex\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SplitFileName\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"stringlcpy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"stringlcat\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"string2wstring\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"wstring2string\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"char2wchar\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"wchar2char\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"formatString\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"stringfTime\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"stringpTime\\\" FUN\\n\"");
#endif
#ifdef _HMITOOLS_EXPORT
	__asm__(".ascii \"plcexport \\\"HMIFileBrowse\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"ListBoxFub\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LogView_init\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LogView_cyclic\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LogView_HMI\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"Editor_fn\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"TrendFn\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"HMI_TabControlFn_Cyclic\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"HMI_Hide\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"HMI_Show\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"HMI_Lock\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"HMI_Unlock\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"HMI_SetFocus\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"HMI_ResetFocus\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"HMI_OpenTouchpad\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"DirectoryFub\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"EditorControl\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ControlTouch\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"ControlDismiss\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"Trend_ZoomScroll\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"LogViewerGetAlarmString\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"LogViewerCreateString\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EditControl_CS_replaceline\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EditControl_CS_append\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EditControl_CS_getline\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EditControl_CS_goto\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EditControl_CS_highlight\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EditControl_CS_insert\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EditControl_CS_read\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"EditControl_CS_replacemarked\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"HMI_FindCurrentTab\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"FindIndexOfString\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"RecipeMgr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"FileQueue\\\" FUB\\n\"");
	__asm__(".ascii \"plcexport \\\"GetDataObjectList\\\" FUN\\n\"");
#endif
#ifdef _RINGBUFLIB_EXPORT
	__asm__(".ascii \"plcexport \\\"BufferCopyItems\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BufferGetItemAdr\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BufferAddToBottom\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BufferAddToTop\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BufferRemoveBottom\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BufferRemoveTop\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BufferRemoveOffset\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BufferBottom\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BufferInit\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BufferDestroy\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BufferClear\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BufferFull\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BufferValid\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"BufferStatus\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"GetTopIndex\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"GetBottomIndex\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"GetNextBottomIndex\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"SetStatusPointer\\\" FUN\\n\"");
	__asm__(".ascii \"plcexport \\\"GetNextTopIndex\\\" FUN\\n\"");
#endif

__asm__(".previous");


#endif /* _LIBRARIES_20231031084308_ */

